name: "iac-test"
on:
  push:
    branches:
       - main
       - stage
    paths:
      - 'terraform/**'
  pull_request:
    branches:
       - main
       - stage
    paths:
      - 'terraform/**'

env:
#credentials for aws depoyment
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#s3 bucket details
BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
AWS_REGION: us-east-1
EKS_CLUSTER: kitops-eks

jobs:
   terraform:
      name: "Apply terraform code changes"
      runs-on: ubuntu-latest
      defaults:
          run:
            shell: bash
            working-directory: ./terraform
      steps:
        - name: checkout source code
          uses: action/checkout@v4

        - name: set up terraform with specified version on the runner
          uses: hashicorp/setup-terraform@v2
          #  with:
          #    terrafrom vesion: 1.6.3
        - name: Terraform init
          id: init
          run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

        - name: Terraform format
          id: format
          run: terraform fmt -check
        
        - name: Terraform validate
          id: validate
          run: terraform validate
       
        - name: Terrform plan
          id: plan
          run: terraform plan -no-color -input=false -out planfile
          continue-on-error: true
        
        - name: Terraform plan status
          if: steps.plan.outcome == 'failure'
          run: exit 1


